version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'g++ main.cpp'
      - persist_to_workspace:
        paths: a.out
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
        at: .
      - run: 'a.out < mkdir valami'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build