version: 2.1
jobs:
  build:
    docker:
       - image: szediablo/build-image:debian-version5
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - a.out
  test:
    docker:
       - image: szediablo/build-image:debian-version5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: './futtat.sh'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build