version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'g++ main.cpp'
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: 'a.out < mkdir valami'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build